name: Trigger Build on circle CI
on:
  workflow_dispatch:
    inputs:
      build-type:
        type: choice
        description: 'Type of build'
        options:
          - android-prod
          - ios-prod
          - android
          - ios
          - build
          - build-prod
jobs:
  trigger-build:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        run: |
          curl -X POST \
          -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d '{ "parameters": { "${{ github.event.inputs.build-type }}": true }, "branch": "v-development" }' \
          https://circleci.com/api/v2/project/github/SvavaCapital/proximus/pipeline
